#!/usr/bin/env ruby
# Generate a Ruby module with the app's config/locales flattened into a table, for an I18n facade.
# Usage: ruby locale_table.rb <rails-app-root> > runtime/rz_i18n_table.rb
require "yaml"
root = ARGV[0] or abort "usage: locale_table.rb <rails-app-root>"
flat = Hash.new { |h, k| h[k] = {} }
walk = lambda do |node, prefix, out|
  case node
  when Hash then node.each { |k, v| walk.(v, prefix.empty? ? k.to_s : "#{prefix}.#{k}", out) }
  when Array then node.each_with_index { |v, i| walk.(v, "#{prefix}.#{i}", out) }
  when nil then nil
  else out[prefix] = node.to_s
  end
end
Dir[File.join(root, "config/locales/**/*.yml")].sort.each do |path|
  (YAML.safe_load(File.read(path), aliases: true, permitted_classes: [Symbol]) || {}).each do |locale, tree|
    walk.(tree, "", flat[locale.to_s])
  end
end
puts "# Generated by locale_table.rb from config/locales — #{flat.values.sum(&:size)} strings."
puts "module RzI18nTable"
puts "  TRANSLATIONS = {"
flat.each do |locale, table|
  puts "    #{locale.inspect} => {"
  table.each { |k, v| puts "      #{k.inspect} => #{v.inspect}," }
  puts "    },"
end
puts "  }"
puts "end"
